"use client";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
type Project={id:string;title:string;category:"Computer vision"|"Security"|"Product";type:string;description:string;stack:string[];image:string;alt:string;href:string;result?:string;caseStudy?:string};
const projects:Project[]=[
{id:"01",title:"PathWise",category:"Computer vision",type:"Road-risk perception prototype",description:"Projects persistent vehicle tracks through a calibrated homography, then uses relative motion for explainable TTC and cut-in warnings.",stack:["Python","YOLO","ByteTrack","OpenCV"],image:"/projects/pathwise-demo.gif",alt:"PathWise road-risk telemetry processing a traffic video",href:"https://github.com/Anantgoel2005/PathWise",result:"540 actor samples in a deterministic six-second reference scenario.",caseStudy:"/projects/pathwise"},
{id:"02",title:"Traffic Intelligence",category:"Computer vision",type:"Detection, tracking, and telemetry",description:"A complete traffic analytics workflow: road activity detection, persistent tracking, incident recording, and an operational dashboard.",stack:["Python","YOLO","ByteTrack","React"],image:"/projects/traffic-overview.jpg",alt:"Traffic Intelligence monitoring dashboard",href:"https://github.com/Anantgoel2005/traffic_monitoring_system"},
{id:"03",title:"Deception Orchestrator",category:"Security",type:"Defensive security console",description:"A self-hostable SOC analyst console that turns honeypot and URL-canary events into MITRE ATT&CK-tagged investigations.",stack:["Python","FastAPI","Next.js","Docker"],image:"/projects/deception.png",alt:"Deception Orchestrator security telemetry dashboard",href:"https://github.com/Anantgoel2005/deception-orchestrator"},
{id:"04",title:"Mouseion",category:"Product",type:"Local-first desktop application",description:"A private offline library for PDF and EPUB collections with reading progress, metadata, favorites, and no cloud dependency.",stack:["TypeScript","React","Electron","Vite"],image:"/projects/mouseion-library.png",alt:"Mouseion private offline library interface",href:"https://github.com/Anantgoel2005/Mouseion"},
{id:"05",title:"Pentest Agent",category:"Security",type:"Scoped assessment tooling",description:"A safety-oriented web assessment tool with explicit scope controls, evidence-first verification, and deterministic reporting.",stack:["Python","HTTPX","Click","CI/CD"],image:"/projects/pentest.svg",alt:"Pentest Agent scope and reporting workflow",href:"https://github.com/Anantgoel2005/pentest-agent"}];
const filters=["All","Computer vision","Security","Product"] as const;
export default function Home(){const[filter,setFilter]=useState<(typeof filters)[number]>("All");const visible=useMemo(()=>projects.filter(p=>filter==="All"||p.category===filter),[filter]);return <main>
<nav className="site-nav" aria-label="Primary navigation"><Link className="wordmark" href="#top">ANANT GOEL<span>.</span></Link><div className="nav-items"><a href="#work">Work</a><a href="#about">About</a><a href="mailto:anantgoel2005@gmail.com">Contact</a></div></nav>
<header className="intro" id="top"><p className="eyebrow">COMPUTER VISION · SECURITY · SYSTEMS</p><h1>I build clear, dependable systems around complex data.</h1><p className="intro-copy">Fourth-year B.Tech Computer Science student based in India. My recent work spans road-risk perception, defensive security tooling, and local-first products.</p><div className="intro-actions"><a className="button button-primary" href="#work">View selected work</a><a className="button" href="https://github.com/Anantgoel2005" target="_blank" rel="noreferrer">GitHub ↗</a><a className="button" href="https://www.linkedin.com/in/ag25goel/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></header>
<section className="featured" aria-labelledby="featured-title"><div className="section-label">01 / FEATURED PROJECT</div><div className="featured-grid"><div><p className="project-category">COMPUTER VISION / SAFETY</p><h2 id="featured-title">PathWise</h2><p>Persistent tracks, calibrated road-plane geometry, and transparent TTC and cut-in rules for a reviewable road-risk pipeline.</p><dl className="evidence-list"><div><dt>540</dt><dd>actor samples</dd></div><div><dt>2.033s</dt><dd>minimum TTC</dd></div><div><dt>33</dt><dd>cut-in frames</dd></div></dl><p className="fine-print">Deterministic six-second scenario outputs - not detector accuracy or deployment-latency claims.</p><div className="project-links"><Link href="/projects/pathwise">Read case study →</Link><a href="https://github.com/Anantgoel2005/PathWise" target="_blank" rel="noreferrer">View source ↗</a></div></div><Link className="featured-image" href="/projects/pathwise" aria-label="Read the PathWise case study"><Image src="/projects/pathwise-demo.gif" alt="PathWise risk telemetry over road footage" fill priority sizes="(max-width: 800px) 100vw, 50vw" /></Link></div></section>
<section className="work" id="work" aria-labelledby="work-title"><div className="work-heading"><div><p className="section-label">02 / SELECTED WORK</p><h2 id="work-title">Projects</h2></div><p>Click through only when you want the evidence.</p></div><div className="filters" aria-label="Filter projects">{filters.map(item=><button type="button" key={item} className={filter===item?"is-active":""} onClick={()=>setFilter(item)}>{item}</button>)}</div><div className="project-grid">{visible.map(project=><article className="project-card" key={project.id}><div className="card-image"><Image src={project.image} alt={project.alt} fill sizes="(max-width: 760px) 100vw, 50vw" /></div><div className="card-content"><p className="project-category">{project.category} · {project.type}</p><h3>{project.title}</h3><p>{project.description}</p>{project.result&&<p className="card-result">{project.result}</p>}<ul>{project.stack.map(item=><li key={item}>{item}</li>)}</ul><div className="project-links">{project.caseStudy&&<Link href={project.caseStudy}>Read case study →</Link>}<a href={project.href} target="_blank" rel="noreferrer">View source ↗</a></div></div></article>)}</div></section>
<section className="about" id="about"><div><p className="section-label">03 / ABOUT</p><h2>Engineering that can be inspected.</h2></div><div><p>I focus on complete workflows: input and data handling, decision logic, APIs, telemetry, testing, and the interface that makes a system useful to a person.</p><p>I am seeking internships, research, and early-career software roles in computer vision, Python systems, and security engineering.</p><a className="text-link" href="mailto:anantgoel2005@gmail.com">Start a conversation →</a></div></section>
<footer><span>© 2026 Anant Goel</span><div><a href="https://github.com/Anantgoel2005" target="_blank" rel="noreferrer">GitHub</a><a href="https://www.linkedin.com/in/ag25goel/" target="_blank" rel="noreferrer">LinkedIn</a><a href="mailto:anantgoel2005@gmail.com">Email</a></div></footer></main>}
